### Create a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email" : "test12@test.com",
    "fullname": "test12",
    "username": "test12",
    "password": "test12"

}

### Sign in a user
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email" : "test@test.com",
    "password": "test"
}

### Get the currently signed in user
GET http://localhost:3000/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMxLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MTY0MTg2NDIsImV4cCI6MTcxNjU5MTQ0Mn0.ze1Sg50k0AyLvD_0769pnQbRYMZFxooEOOR0lj0P3v0


### Find a particular user with a given id
GET http://localhost:3000/users/30

### Find all users with a given email
GET http://localhost:3000/users?email=a@a.com

### Delete the currently logedin user
DELETE http://localhost:3000/users/delaccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJ1c2VybmFtZSI6Im5ldzEwIiwiZW1haWwiOiJuZXcxMEB0ZXN0LmNvbSIsImlhdCI6MTcwNDc5NTkzNSwiZXhwIjoxNzA0ODgyMzM1fQ.TNdjntUYAGPY8VMVGo-gL-TAe5FkGfnj7MUmVdVcpPE

### Update a user 
PATCH http://localhost:3000/users/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MTU5Mjg2MDgsImV4cCI6MTcxNjAxNTAwOH0.AK8HQE24BnGVS35162x6_orFIylbirD03ZHlewmrVGA
Content-Type: application/json

{
    "email": "test2@test.com"
}

### Update a user change username
PATCH http://localhost:3000/users/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MTU5Mjg2MDgsImV4cCI6MTcxNjAxNTAwOH0.AK8HQE24BnGVS35162x6_orFIylbirD03ZHlewmrVGA
Content-Type: application/json

{
    "username": "test2"
}

### Change user password
PATCH http://localhost:3000/users/changePass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMwLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MTU5Mjg2MDgsImV4cCI6MTcxNjAxNTAwOH0.AK8HQE24BnGVS35162x6_orFIylbirD03ZHlewmrVGA
Content-Type: application/json

{
    "currentPassword" : "test",
    "newPassword" : "test2"
}

### Add Movie to watchlist
PATCH http://localhost:3000/users/add/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJ1c2VybmFtZSI6Im5ldzEwIiwiZW1haWwiOiJuZXcxMEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgzNzU1NSwiZXhwIjoxNzA0OTIzOTU1fQ.r9EiC0CCItAiLfn-QqjQxoc6OY64rdQTgXZPgYYDk_Q

### Delete Movie from watchlist
DELETE http://localhost:3000/users/del/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJ1c2VybmFtZSI6Im5ldzEwIiwiZW1haWwiOiJuZXcxMEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgzNzU1NSwiZXhwIjoxNzA0OTIzOTU1fQ.r9EiC0CCItAiLfn-QqjQxoc6OY64rdQTgXZPgYYDk_Q


### Get all The Movies from the watchlist
GET  http://localhost:3000/users/watchlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJ1c2VybmFtZSI6ImIiLCJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUwODE5ODEsImV4cCI6MTcwNTE2ODM4MX0.83CkJDqtlKJbFJ9JXlZQHXN7GU-2OGRF6cvhAeIx0BU

### Get all the movies from a particular cinema
GET http://localhost:3000/users/cinema/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJ1c2VybmFtZSI6ImIiLCJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUwNzM4NTcsImV4cCI6MTcwNTE2MDI1N30.Svp3N0YTwbfiJt8wUyP0VDKDsfFfUsUHCnuFrzbxwng

### Get movie by id
GET http://localhost:3000/users/movie/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJ1c2VybmFtZSI6ImIiLCJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUwNzM4NTcsImV4cCI6MTcwNTE2MDI1N30.Svp3N0YTwbfiJt8wUyP0VDKDsfFfUsUHCnuFrzbxwng

