### Add Movie To watchlist
POST  http://localhost:3000/watchlist/add/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM4LCJ1c2VybmFtZSI6InRlc3QxMiIsImVtYWlsIjoidGVzdDEyQHRlc3QuY29tIiwiaWF0IjoxNzE3MDEzODg5LCJleHAiOjE3MTcxODY2ODl9.L-yEW1GoT0hTA6Hk4uWNVWb2U1z54TLHXD35_0pW2uA

### Remove Movie From watchlist
DELETE http://localhost:3000/watchlist/remove/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMxLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MTYxMjgzNzcsImV4cCI6MTcxNjMwMTE3N30.xsscnwggfciNVZm_tz-5u7qIq5NY6gxjdSgkwpeka3I


### Get Watchlist
GET http://localhost:3000/watchlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM4LCJ1c2VybmFtZSI6InRlc3QxMiIsImVtYWlsIjoidGVzdDEyQHRlc3QuY29tIiwiaWF0IjoxNzE3MDEzODg5LCJleHAiOjE3MTcxODY2ODl9.L-yEW1GoT0hTA6Hk4uWNVWb2U1z54TLHXD35_0pW2uA
